version: '3'

services:
    scan-coordinator:
      depends_on:
        - clamav
        - rabbit
        - minio
      environment:
        - BYPASS_CLAMAV=false
        - AMQP_HOST=rabbit
        - AMQP_VHOST=/tfrs
        - AMQP_USER=rabbitmq
        - AMQP_PASSWORD=rabbitmq
        - CLAMAV_HOST=clamav
      env_file:
      - minio.env
      command: >
        bash -c
        "/wfi/wait-for-it.sh -t 14400 rabbit:5672 &&
        /wfi/wait-for-it.sh -t 14400 clamav:3310 &&
        scan-coordinator"
      build:
        dockerfile: Dockerfile
        context: ./security-scan/scan-coordinator
    clamav:
      image: mkodockx/docker-clamav
      ports:
        - 3310:3310
    rabbit:
        image: rabbitmq:3.7-management
        hostname: "rabbit"
        environment:
            - RABBITMQ_DEFAULT_USER=rabbitmq
            - RABBITMQ_DEFAULT_PASS=rabbitmq
            - RABBITMQ_DEFAULT_VHOST=/tfrs
            - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbit log_levels [{connection,error}]
        ports:
            - 15672:15672
            - 5672:5672
    minio:
      image: minio/minio
      volumes:
        - minio_data:/export
      environment:
        MINIO_ACCESS_KEY: 296e92217fa3479aaf9cc9641fdb6e0a
        MINIO_SECRET_KEY: 778eecb24d7743b5a1b56bbf36a29d62
      ports:
        - 9000:9000
      command: "server /export"
    smtplogger:
      build:
        context: ./smtplogger
        dockerfile: Dockerfile-smtplogger
      ports:
        - 2500:2500
volumes:
    minio_data:
