apiVersion: template.openshift.io/v1
kind: Template
parameters:
- name: DJANGO_SECRET_KEY
  description: "secret used by Django"
  from: "[a-zA-Z0-9]{50}"
  generate: expression
  required: true
objects:
- apiVersion: v1
  kind: Secret
  metadata:
    annotations: null
    name: django-secret-key
  stringData:
    DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}

    